server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}
    username: {DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update
